name: flutter_app_orientation
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_pro: ^0.0.13


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.9+1
  folding_cell: ^0.1.2
  cloud_firestore:
  url_launcher: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/1_poster.jpeg
    - assets/images/2_poster.jpg
    - assets/images/3_poster.jpg
    - assets/images/bmu_logo.jpg
    - assets/images/sanyal.png

    - assets/images/clubs_logos/NSS-Logo.jpeg
    - assets/images/club_heads/nss/nss-president.jpg
    - assets/images/club_heads/nss/nss-vicepresident.jpg

    - assets/images/clubs_logos/robotics.jpg
    - assets/images/club_heads/robotics/robotics-president.jpg
    - assets/images/club_heads/robotics/robotics-vicepresident.jpg

    - assets/images/clubs_logos/speakeasy.jpg
    - assets/images/club_heads/speakeasy/speakeasy-president.png
    - assets/images/club_heads/speakeasy/speakeasy-vicepresident.jpg

    - assets/images/clubs_logos/acm.jpeg
    - assets/images/club_heads/acm/acm-president.jpg
    - assets/images/club_heads/acm/acm-vicepresident.jpg

    - assets/images/clubs_logos/sierra_logo.png
    - assets/images/club_heads/sierra/sierra-president.jpeg
    - assets/images/club_heads/sierra/sierra-vicepresident.jpeg

    - assets/images/clubs_logos/socialmedia_logo.jpg
    - assets/images/club_heads/socialmedia/socialmedia-president.jpg
    - assets/images/club_heads/socialmedia/socialmedia-vicepresident.jpg

    - assets/images/clubs_logos/savera_logo.jpg
    - assets/images/club_heads/savera/savera-president.jpg
    - assets/images/club_heads/savera/savera-vicepresident.jpg

    - assets/images/clubs_logos/tsec_logo.jpg
    - assets/images/club_heads/tsec/tsec-president.jpg
    - assets/images/club_heads/tsec/tsec-vicepresident.jpg

    - assets/images/clubs_logos/culinary_logo.jpg
    - assets/images/club_heads/culinary/culinary-president.jpg
    - assets/images/club_heads/culinary/culinary-vicepresident.jpg

    - assets/images/clubs_logos/adventure_logo.jpg
    - assets/images/club_heads/adventure/adventure-president.jpg
    - assets/images/club_heads/adventure/adventure-vicepresident.jpg

    - assets/images/clubs_logos/fight_logo.jpg
    - assets/images/club_heads/fight/fight-president.jpg
    - assets/images/club_heads/fight/fight-vicepresident.jpg

    - assets/images/clubs_logos/udaan_logo.jpg
    - assets/images/club_heads/udaan/udaan-president.jpg
    - assets/images/club_heads/udaan/udaan-vicepresident.jpg

    - assets/images/clubs_logos/pac_logo.jpg
    - assets/images/club_heads/pac/pac-president.jpg
    - assets/images/club_heads/pac/pac-vicepresident.jpg

    - assets/images/clubs_logos/strokes_logo.jpg
    - assets/images/club_heads/strokes/strokes-president.jpg
    - assets/images/club_heads/strokes/strokes-vicepresident.jpg

    - assets/images/clubs_logos/enactus_logo.jpg
    - assets/images/club_heads/enactus/enactus-president.jpg
    - assets/images/club_heads/enactus/enactus-vicepresident.jpg

    - assets/images/clubs_logos/liquid_logo.jpg
    - assets/images/club_heads/liquid/liquid-president.jpg
    - assets/images/club_heads/liquid/liquid-vicepresident.jpg

    - assets/images/clubs_logos/sata_logo.jpg
    - assets/images/club_heads/sata/sata-president.jpg
    - assets/images/club_heads/sata/sata-vicepresident.jpg

    - assets/images/clubs_logos/automobile_logo.jpg
    - assets/images/club_heads/automobile/automobile-president.jpg
    - assets/images/club_heads/automobile/automobile-vicepresident.jpg

    - assets/images/clubs_logos/photography_logo.jpg
    - assets/images/club_heads/photography/photography-president.jpg
    - assets/images/club_heads/photography/photography-vicepresident.jpg

    - assets/images/clubs_logos/environmental_logo.png
    - assets/images/club_heads/environmental/environmental-president.jpg
    - assets/images/club_heads/environmental/environmental-vicepresident.jpg

    - assets/images/clubs_logos/scimat_logo.jpg
    - assets/images/club_heads/scimat/scimat-president.jpg
    - assets/images/club_heads/scimat/scimat-vicepresident.jpg
  #   assets:
#    - images/a_dot_burr.jpeg
#    - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
